# Generated by Django 2.0.6 on 2018-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180808_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomized',
            name='role',
        ),
        migrations.AddField(
            model_name='usercustomized',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
    ]
