# Generated by Django 2.0.6 on 2018-08-11 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_roomchat_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
